### ISSUE TITLE
Citrix VDA server .exe download incomplete

### ISSUE THREAD

**Issue by getvpro** [JonathanPitre/Apps#11]
For script, https://github.com/JonathanPitre/Apps/blob/master/Citrix/Virtual%20Delivery%20Agent/Install-ServerMCS-CR.ps1

Downloads are coming at 33 KB, should be approx 500 MB

**Comment by JonathanPitre** [comment]
Require an update of Ryan Butler Citrix Download Scrapper
https://github.com/ryancbutler/Citrix_DL_Scrapper

This is gonna take me a while

**Comment by JonathanPitre** [comment]
Since Citrix now forced MFA on their downloads page, this can no longer be scripted. VDA binaries must be downloaded manually for now.
