### ISSUE TITLE
Language Pack Issue

### ISSUE THREAD

**Issue by jmpigeoniti** [JonathanPitre/Apps#13]
When it's time to add language ligne 315
I have issue to install  
WARNING: Failed to add package \\x.x.x.x\homes\x\software\Apps-master\Microsoft\Language Pack\Microsoft-Windows-Client-Language-Pack_x64_fr-ca.cab
WARNING: Add-WindowsPackage failed. Error code = 0x800f081e

I use it on windows 2022 Server.

**Comment by JonathanPitre** [comment]
The script is made for Windows 10 Multi-session only. I need to add code for OS detection.

I need to look into this code as well to see if I can merge it.
https://github.com/JimMoyle/Install-LanguagePack/blob/master/Install-LanguagePack.ps1

**Comment by JonathanPitre** [comment]
More docs to review
https://github.com/Azure/RDS-Templates/blob/d6c7405bf7218b79a84cea17c0f4fa70fe664230/CustomImageTemplateScripts/CustomImageTemplateScripts_2023-03-01/InstallLanguagePacks.ps1

https://blogs.mycugc.org/2023/03/07/citrix-hdx-optimization/
