### ISSUE TITLE
Adobe Acrobat DC - x64 - Language OS

### ISSUE THREAD

**Issue by asterix4you** [JonathanPitre/Apps#14]
Hi Jonathan,
I have installed Adobe Acrobat DC x64 with your poweschell script. At the end of the installation there are only two languages ​​to select: France and English. The OS language (Italian) is not selected. How can I fix?

**Comment by JonathanPitre** [comment]
Hi asterix4you, you can fix it by modifying the MST file with the Adobe Customization Wizard and adding back the Italian language.

https://www.adobe.com/devnet-docs/acrobatetk/tools/Wizard/basics.html

If you provide your own MST and it already exists where the script resides, it should not download the one I provided on GitHub.

**Comment by JonathanPitre** [comment]
All languages are now installed by default, the MST was modified accordingly.
