### ISSUE TITLE
[Bug] Script to install Citrix Workspace App for workstation doesn't report the application version

### ISSUE THREAD

**Issue by Kirov001** [JonathanPitre/Apps#15]
It doesn't seem to want to download the last version.
In the script the Evergreen module returns the wrong version for the CitrixWorkspaceApp.
![evergreen](https://github.com/JonathanPitre/Apps/assets/149400736/e23a15fe-2266-497e-8c8d-3d1357228ef9)

**Comment by JonathanPitre** [comment]
The Evergreen issue was reported here.
https://github.com/aaronparker/evergreen/issues/578

In the meantime, I changed the script the grab the version for the setup name instead.
